package casher;

import java.awt.Color;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Driver;
import java.sql.DriverManager;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.*;
import java.awt.Image;

public class RegisterForm extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    
    String Nama;
    String NamaID;
    String Password;
    String Jeniskelamin;
    String filePath;
    
    public RegisterForm() {
        initComponents();
        this.getContentPane().setBackground(new Color(236,221,15));
        connect();
        
        passwordTxt.setText("");
    }
    
    public void connect()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/myney", "root", "");
            stat = con.createStatement();
        } catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        namaidTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        fotoTxt = new javax.swing.JTextField();
        fotoChooser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lakiRBtn = new javax.swing.JRadioButton();
        perempuanRBtn = new javax.swing.JRadioButton();
        selesaiBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        MasukBtn = new javax.swing.JButton();
        ulangiBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(236, 221, 15));
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulir Daftar");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel2.setText("Nama");

        namaTxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel3.setText("Nama ID");

        namaidTxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel4.setText("Password");

        passwordTxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        passwordTxt.setText("jPasswordField1");

        jLabel5.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel5.setText("Foto");

        fotoTxt.setEditable(false);
        fotoTxt.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N

        fotoChooser.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        fotoChooser.setText("...");
        fotoChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fotoChooserActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        jLabel6.setText("Jenis Kelamin");

        lakiRBtn.setBackground(new java.awt.Color(255, 255, 255));
        jenisKelamin.add(lakiRBtn);
        lakiRBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        lakiRBtn.setText("Laki-laki");

        perempuanRBtn.setBackground(new java.awt.Color(255, 255, 255));
        jenisKelamin.add(perempuanRBtn);
        perempuanRBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        perempuanRBtn.setText("Perempuan");

        selesaiBtn.setBackground(new java.awt.Color(57, 159, 221));
        selesaiBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        selesaiBtn.setForeground(new java.awt.Color(255, 255, 255));
        selesaiBtn.setText("Selesai");
        selesaiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        jLabel7.setText("Sudah memiliki akun?");

        MasukBtn.setBackground(new java.awt.Color(57, 159, 221));
        MasukBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 13)); // NOI18N
        MasukBtn.setForeground(new java.awt.Color(255, 255, 255));
        MasukBtn.setText("Masuk");
        MasukBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasukBtnActionPerformed(evt);
            }
        });

        ulangiBtn.setBackground(new java.awt.Color(57, 159, 221));
        ulangiBtn.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 14)); // NOI18N
        ulangiBtn.setForeground(new java.awt.Color(255, 255, 255));
        ulangiBtn.setText("Ulangi");
        ulangiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangiBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(namaTxt)
                                .addComponent(namaidTxt)
                                .addComponent(passwordTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lakiRBtn)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanRBtn))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ulangiBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(selesaiBtn))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(fotoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(fotoChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MasukBtn)
                        .addGap(12, 12, 12)))
                .addContainerGap(247, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(namaidTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lakiRBtn)
                    .addComponent(perempuanRBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fotoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoChooser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selesaiBtn)
                    .addComponent(ulangiBtn))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(MasukBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MasukBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasukBtnActionPerformed
        LoginForm loginForm = new LoginForm();
        this.dispose();
        loginForm.setVisible(true);
    }//GEN-LAST:event_MasukBtnActionPerformed

    private void ulangiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangiBtnActionPerformed
        namaTxt.setText("");
        namaidTxt.setText("");
        passwordTxt.setText("");
        jenisKelamin.clearSelection();
        fotoTxt.setText("");
    }//GEN-LAST:event_ulangiBtnActionPerformed

    private void selesaiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiBtnActionPerformed
        try
        {
            Nama = namaTxt.getText();
            NamaID = namaidTxt.getText();
            Password = passwordTxt.getText();
            
            if(lakiRBtn.isSelected())
            {
                Jeniskelamin = lakiRBtn.getText();
            } else if(perempuanRBtn.isSelected())
            {
                Jeniskelamin = perempuanRBtn.getText();
            }
            
            if(Nama.isEmpty() || NamaID.isEmpty() || Password.isEmpty() || Jeniskelamin.isEmpty() || filePath.isEmpty())
            {
                JOptionPane.showMessageDialog(this, "Lengkapi Data Anda Terlebih Dahulu!", "PERINGATAN", JOptionPane.WARNING_MESSAGE);
            } else
            {
                PreparedStatement ps = con.prepareStatement("insert into user(id, password, nama, jeniskelamin, foto) values(?,?,?,?,?)");
                InputStream is = new FileInputStream(new File(filePath));
                ps.setString(1, NamaID);
                ps.setString(2, Password);
                ps.setString(3, Nama);
                ps.setString(4, Jeniskelamin);
                ps.setBlob(5, is);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Registrasi Berhasil");
                
                namaTxt.setText("");
                namaidTxt.setText("");
                passwordTxt.setText("");
                jenisKelamin.clearSelection();
                fotoTxt.setText("");
                filePath = ""; 
            }
        } catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, "Gagal Mendaftar");
        }
    }//GEN-LAST:event_selesaiBtnActionPerformed

    private void fotoChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fotoChooserActionPerformed
        try
        {
            JFileChooser fileChooser = new JFileChooser();
            FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("JGP, PNG, and GIF", "jpg", "png", "gif");
            fileChooser.setFileFilter(fileFilter);
            fileChooser.showOpenDialog(null);
            File foto = fileChooser.getSelectedFile();
            Image image = ImageIO.read(foto);
            filePath = foto.getAbsolutePath();
            fotoTxt.setText(filePath);
        } catch(Exception ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_fotoChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MasukBtn;
    private javax.swing.JButton fotoChooser;
    private javax.swing.JTextField fotoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JRadioButton lakiRBtn;
    private javax.swing.JTextField namaTxt;
    private javax.swing.JTextField namaidTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JRadioButton perempuanRBtn;
    private javax.swing.JButton selesaiBtn;
    private javax.swing.JButton ulangiBtn;
    // End of variables declaration//GEN-END:variables
}
